name: CI / CD Pipeline with Argocd

on: 
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image 
        uses: docker/build-push-action@v6.18.0
        with: 
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your-disc:v${{ github.run_number }}
  
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPOSITORY }}
          path: projetoci-cd
          token: ${{ secrets.TOKEN }}

      - name: Update manifest
        run: |
          cd projetoci-cd
          sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/your-disc:.*|image: ${{ secrets.DOCKER_USERNAME }}/your-disc:v${{ github.run_number }}|' k8s/deployment.yaml

      - name: Commit and push manifest changes
        run: |
          cd projetoci-cd
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add k8s/deployment.yaml
          git commit -m "ci: Update image to v${{ github.run_number }}"
          git push origin main